[package]
name = "FAMinter"
version = "1.0.0"
authors = []

[addresses]
aptos_framework = "0x1"
FAMinter = "_"

[dev-addresses]
FAMinter = "0x2"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
